version: 2.1
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.2.3
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.13.1-browsers
        environment:
          CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - restore_cache:
          key: Mena-PackageFront-{{ checksum "package-lock.json" }}
      - run: npm run frontend:install
      - save_cache:
          key: Mena-PackageFront-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - restore_cache:
          key: Mena-PackageBack-{{ checksum "package-lock.json" }}
      - run: npm run backend:install
      - save_cache:
          key: Mena-PackageBack-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build

workflows:
  sample:
    jobs:
      - build-and-test