version: 2.1
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.2.3
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.13.1-browsers
        environment:
          CHROME_BIN: /usr/bin/google-chrome
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - aws-cli/setup
      - checkout
      - eb/setup
      - checkout
      - restore_cache:
          key: Mena-PackageFront-{{ checksum "udagram-frontend/package-lock.json" }}
      - run: npm run frontend:install
      - save_cache:
          key: Mena-PackageFront-{{ checksum "udagram-frontend/package-lock.json" }}
          paths:
            - "udagram-frontend/node_modules"
      - checkout
      - restore_cache:
          key: Mena-PackageBack-{{ checksum "udagram-api/package-lock.json" }}
      - run: npm run backend:install
      - save_cache:
          key: Mena-PackageBack-{{ checksum "udagram-frontend/package-lock.json" }}
          paths:
            - "udagram-api/node_modules"      
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      - run:
          name: Back-End test
          command: |
            npm run backend:test
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy BackEnd
          command: |
            npm run backend:deploy

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main